# 数据配置
data:
  path: "data/scene"
  images_path: "images"
  sparse_path: "sparse/0"
  output_path: "output"

# 训练配置
training:
  iterations: 30000
  batch_size: 1
  eval_interval: 1000
  save_interval: 5000
  log_interval: 100

# 学习率配置
learning_rates:
  position:
    init: 0.00016
    final: 0.0000016
    delay_mult: 0.01
    max_steps: 30000
  feature: 0.0025
  opacity: 0.05
  scaling: 0.005
  rotation: 0.001

# 密度控制配置
density_control:
  densify_from_iter: 500
  densify_until_iter: 15000
  densify_grad_threshold: 0.0002
  densify_interval: 100
  prune_opacity_threshold: 0.005
  prune_interval: 1000

# 渲染配置
rendering:
  image_height: 800
  image_width: 800
  background_color: [0.0, 0.0, 0.0]

# 损失函数配置
loss:
  lambda_dssim: 0.2

# 系统配置
system:
  device: "cuda"
  num_workers: 4
  pin_memory: true